<a href="https://colab.research.google.com/github/manavsharma111/Machine-Learning/blob/main/Titanic_Survival_Prediction_logistic_regression_knn_decision_tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv("Titanic-Dataset.csv")

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [20]:
df.drop(["Cabin","Pclass","Ticket","Name"], axis=1, inplace=True, errors='ignore')

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Sex          889 non-null    object
 3   Age          889 non-null    float64
 4   SibSp        889 non-null    int64
 5   Parch        889 non-null    int64
 6   Fare         889 non-null    float64
 7   Embarked     889 non-null    object
dtypes: float64(2), int64(4), object(2)
memory usage: 62.5+ KB

In [22]:
df["Age"].fillna(df["Age"].mean(), inplace=True)

In [23]:
df.dropna(subset=["Embarked"], inplace=True)

In [53]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  889 non-null    int64
 1   Survived     889 non-null    int64
 2   Sex          889 non-null    int64
 3   Age          889 non-null    float64
 4   SibSp        889 non-null    int64
 5   Parch        889 non-null    int64
 6   Fare         889 non-null    float64
 7   Embarked     889 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 62.5 KB

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [28]:
df.head()

   PassengerId  Survived     Sex   Age  SibSp  Parch     Fare Embarked
0            1         0    male  22.0      1      0   7.2500        S
1            2         1  female  38.0      1      0  71.2833        C
2            3         1  female  26.0      0      0   7.9250        S
3            4         1  female  35.0      1      0  53.1000        S
4            5         0    male  35.0      0      0   8.0500        S

In [33]:
df["Sex"]=le.fit_transform(df["Sex"])
df["Embarked"]=le.fit_transform(df["Embarked"])

In [35]:
df.drop(["Embark"], axis=1, inplace=True)

In [36]:
df.head()

   PassengerId  Survived  Sex   Age  SibSp  Parch     Fare  Embarked
0            1         0    1  22.0      1      0   7.2500         2
1            2         1    0  38.0      1      0  71.2833         0
2            3         1    0  26.0      0      0   7.9250         2
3            4         1    0  35.0      1      0  53.1000         2
4            5         0    1  35.0      0      0   8.0500         2

In [38]:
X=df.drop("Survived", axis=1)
Y=df["Survived"]

LOGISTIC REGRASSION

In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2, random_state=42)

In [47]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
model=LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [48]:
Y_pred=model.predict(X_test)

In [49]:
Y_pred

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [50]:
Y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: Survived, Length: 178, dtype: int64

In [52]:
confusion_matrix(Y_test, Y_pred)

array([[91, 18],
       [18, 51]])

In [56]:
accuracy = accuracy_score(Y_test, Y_pred)
print(f"Accuracy Score: {accuracy:.4f}")

Accuracy Score: 0.7978

In [58]:
from sklearn.metrics import precision_score
precision = precision_score(Y_test, Y_pred)
print(f"Precision Score: {precision:.4f}")

Precision Score: 0.7391

In [59]:
from sklearn.metrics import recall_score, f1_score

recall = recall_score(Y_test, Y_pred)
f1 = f1_score(Y_test, Y_pred)

print(f"Recall Score: {recall:.4f}")
print(f"F1 Score: {f1:.4f}")

Recall Score: 0.7391
F1 Score: 0.7391

In [60]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import LogisticRegression

# Define the parameter grid for Logistic Regression
param_grid = {
    'C': [0.001, 0.01, 0.1, 1, 10, 100],
    'solver': ['liblinear', 'lbfgs'],
    'penalty': ['l1', 'l2']
}

# Create a GridSearchCV object
# Note: 'l1' penalty is only supported by 'liblinear' solver
# 'lbfgs' solver only supports 'l2' penalty
# We'll handle this by adjusting the grid for each solver in GridSearchCV implicitly.
# GridSearchCV will automatically skip invalid combinations.

grid_search = GridSearchCV(LogisticRegression(max_iter=200), param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Fit GridSearchCV to the training data
grid_search.fit(X_train, Y_train)

# Print the best parameters and best score
print(f"Best parameters: {grid_search.best_params_}")
print(f"Best cross-validation accuracy: {grid_search.best_score_:.4f}")

# Get the best model
best_model = grid_search.best_estimator_

# Make predictions with the best model
Y_pred_tuned = best_model.predict(X_test)

# Evaluate the tuned model on the test set
accuracy_tuned = accuracy_score(Y_test, Y_pred_tuned)
precision_tuned = precision_score(Y_test, Y_pred_tuned)
recall_tuned = recall_score(Y_test, Y_pred_tuned)
f1_tuned = f1_score(Y_test, Y_pred_tuned)

print(f"Tuned Model Accuracy: {accuracy_tuned:.4f}")
print(f"Tuned Model Precision: {precision_tuned:.4f}")
print(f"Tuned Model Recall: {recall_tuned:.4f}")
print(f"Tuned Model F1 Score: {f1_tuned:.4f}")

Best parameters: {'C': 100, 'penalty': 'l2', 'solver': 'liblinear'}
Best cross-validation accuracy: 0.7932
Tuned Model Accuracy: 0.7921
Tuned Model Precision: 0.7286
Tuned Model Recall: 0.7391
Tuned Model F1 Score: 0.7338

In [62]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83       109
           1       0.74      0.74      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

In [63]:
df

     PassengerId  Survived  Sex        Age  SibSp  Parch     Fare  Embarked
0              1         0    1  22.000000      1      0   7.2500         2
1              2         1    0  38.000000      1      0  71.2833         0
2              3         1    0  26.000000      0      0   7.9250         2
3              4         1    0  35.000000      1      0  53.1000         2
4              5         0    1  35.000000      0      0   8.0500         2
..           ...       ...  ...        ...    ...    ...      ...       ...
886          887         0    1  27.000000      0      0  13.0000         2
887          888         1    0  19.000000      0      0  30.0000         2
888          889         0    0  29.699118      1      2  23.4500         2
889          890         1    1  26.000000      0      0  30.0000         0
890          891         0    1  32.000000      0      0   7.7500         1

[889 rows x 8 columns]

In [64]:
X_train

     PassengerId  Sex        Age  SibSp  Parch      Fare  Embarked
708          709    0  22.000000      0      0  151.5500         2
240          241    0  29.699118      1      0   14.4542         0
382          383    1  32.000000      0      0    7.9250         2
792          793    0  29.699118      8      2   69.5500         2
683          684    1  14.000000      5      2   46.9000         2
..           ...  ...        ...    ...    ...       ...       ...
107          108    1  29.699118      0      0    7.7750         2
271          272    1  25.000000      0      0    0.0000         2
862          863    0  48.000000      0      0   25.9292         2
436          437    0  21.000000      2      2   34.3750         2
103          104    1  33.000000      0      0    8.6542         2

[711 rows x 7 columns]

In [65]:
X_test

     PassengerId  Sex   Age  SibSp  Parch      Fare  Embarked
281          282    1  28.0      0      0    7.8542         2
435          436    0  14.0      1      2  120.0000         2
39            40    0  14.0      1      0   11.2417         0
418          419    1  30.0      0      0   13.0000         2
585          586    0  18.0      0      2   79.6500         2
..           ...  ...   ...    ...    ...       ...       ...
433          434    1  17.0      0      0    7.1250         2
807          808    0  18.0      0      0    7.7750         2
25            26    0  38.0      1      5   31.3875         2
85            86    0  33.0      3      0   15.8500         2
10            11    0   4.0      1      1   16.7000         2

[178 rows x 7 columns]

KNN

In [66]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [67]:
X_train_scaled=scaler.fit_transform(X_train)
X_test_scaled=scaler.transform(X_test)

In [68]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

In [70]:
knn_model=KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, Y_train)

KNeighborsClassifier()

In [72]:
Y_pred_knn=knn_model.predict(X_train_scaled)
Y_pred_knn

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0])

In [73]:
acuracy_knn=accuracy_score(Y_train, Y_pred_knn)
acuracy_knn

0.8368495077355836

In [74]:
knn_confussion_matrix=confusion_matrix(Y_train, Y_pred_knn)
knn_confussion_matrix

array([[390,  50],
       [ 66, 205]])

NEIVE BAYES

In [77]:
from sklearn.naive_bayes import GaussianNB
model_nb=GaussianNB()
model_nb.fit(X_train, Y_train)

GaussianNB()

In [82]:
Y_pred_nb=model_nb.predict(X_test)
Y_pred_nb

array([0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 1])

In [80]:
Y_test

281    0
435    1
39     1
418    0
585    1
      ..
433    0
807    0
25     1
85     1
10     1
Name: Survived, Length: 178, dtype: int64

In [83]:
confusion_matrix_nb=confusion_matrix(Y_test, Y_pred_nb)
confusion_matrix_nb

array([[90, 19],
       [17, 52]])

In [85]:
accuracy_nb=accuracy_score(Y_test, Y_pred_nb)
precision_nb=precision_score(Y_test, Y_pred_nb)
recall_nb=recall_score(Y_test, Y_pred_nb)
f1_nb=f1_score(Y_test, Y_pred_nb)

print(f"Accuracy: {accuracy_nb:.4f}")
print(f"Precision: {precision_nb:.4f}")
print(f"Recall: {recall_nb:.4f}")
print(f"F1: {f1_nb:.4f}")

Accuracy: 0.7978
Precision: 0.7324
Recall: 0.7536
F1: 0.7429

In [87]:
print(classification_report(Y_test, Y_pred_nb))

              precision    recall  f1-score   support

           0       0.84      0.83      0.83       109
           1       0.73      0.75      0.74        69

    accuracy                           0.80       178
   macro avg       0.79      0.79      0.79       178
weighted avg       0.80      0.80      0.80       178

Decission Tree

In [89]:
from sklearn.tree import DecisionTreeClassifier

In [90]:
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, Y_train)

DecisionTreeClassifier(random_state=42)

In [91]:
Y_pred_dt = dt_model.predict(X_test)

accuracy_dt = accuracy_score(Y_test, Y_pred_dt)
precision_dt = precision_score(Y_test, Y_pred_dt)
recall_dt = recall_score(Y_test, Y_pred_dt)
f1_dt = f1_score(Y_test, Y_pred_dt)
conf_matrix_dt = confusion_matrix(Y_test, Y_pred_dt)

print(f"Decision Tree Accuracy: {accuracy_dt:.4f}")
print(f"Decision Tree Precision: {precision_dt:.4f}")
print(f"Decision Tree Recall: {recall_dt:.4f}")
print(f"Decision Tree F1 Score: {f1_dt:.4f}")
print("Decision Tree Confusion Matrix:\n", conf_matrix_dt)
print("\nDecision Tree Classification Report:\n", classification_report(Y_test, Y_pred_dt))

Decision Tree Accuracy: 0.7528
Decision Tree Precision: 0.6506
Decision Tree Recall: 0.7826
Decision Tree F1 Score: 0.7105
Decision Tree Confusion Matrix:
 [[80 29]
 [15 54]]

Decision Tree Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.73      0.78       109
           1       0.65      0.78      0.71        69

    accuracy                           0.75       178
   macro avg       0.75      0.76      0.75       178
weighted avg       0.77      0.75      0.76       178